### ISSUE TITLE
Gradle files (such as gradlew, gradlew.bat, and the gradle wrapper) are missing

### ISSUE THREAD

**Issue by SansIsTyping** [katzenpapst/amunra#11]
These files are essential to allowing others to contribute to code with setupDecompWorkspace and build. Without these files, people will have to manually install the Gradle wrapper themselves, which is a pain.

**Comment by katzenpapst** [comment]
Is it even "legal" to add these files? Galacticraft doesn't add these, either

**Comment by SansIsTyping** [comment]
@katzenpapst yes it is. All mod creators use them and must be added to the repo for others to collaborate. Just because GalactiCraft doesn't add them *doesn't mean everyone else doesn't add them as well.*

**Comment by vos3464** [comment]
please add them

**Comment by katzenpapst** [comment]
Ok fine, I'll add them.

**Comment by SansIsTyping** [comment]
@katzenpapst One more thing, I've noticed that you have local API files in your lib or libs folder if I am correct? Would you mind either giving out the apis that you have used in the project in a README.md or removing /lib and /libs from the .gitignore file? Thanks.

**Comment by katzenpapst** [comment]
There are just the galacticraft-dev jars. I'm probably doing it wrong, but I'm not sure how to do it the "right" way

**Comment by SansIsTyping** [comment]
@katzenpapst I'll take a look at it then and I'll get back to you.

**Comment by SansIsTyping** [comment]
@katzenpapst You have imported the galacticraft-dev jars alright, but do you mind telling me what version of galacticraft you are using to create your addon, as the .gitignore also ignores the /libs folder which I need to build your addon (because it contains the galacticraft-dev jars as you had stated).

**Comment by katzenpapst** [comment]
Build 463. Right now I added them into the Java Build Path in Eclipse.

**Comment by katzenpapst** [comment]
anyway, gradle stuff is in develop now

**Comment by SansIsTyping** [comment]
@katzenpapst awsome. can you also add in the libs folder? that has the dev jars and it's needed to build the thing

**Comment by katzenpapst** [comment]
I really don't think I should add Galacticraft's Jars to my git repo.

**Comment by SansIsTyping** [comment]
@katzenpapst then make a README.md explaining how to do so manually so that others can contribute. Or don't at this point it's your choice. The gradle stuff was vital but this is optional.
