### ISSUE TITLE
Player and Mobs die when landing on ground after leaving Gravity Machines Vertical Gravity

### ISSUE THREAD

**Issue by vos3464** [katzenpapst/amunra#20]
even when power is 3 and the box is 3 or 1 block up player and mobs die.
also can you make liquids go up when gravity is vertical?

**Comment by katzenpapst** [comment]
Liquids: no.
For the rest: what do you mean? Please give more detailed bug reports.

**Comment by katzenpapst** [comment]
should be fixed now
