### ISSUE TITLE
Worldprovider/mothership problem

### ISSUE THREAD

**Issue by Rory0merchury** [katzenpapst/amunra#21]
worldprovider problem with amunra 0.3.8 
its basically crashing the server 1.7.10

http://pastebin.com/5uwCcGet

Worldprovider/Mothership

**Comment by katzenpapst** [comment]
Have you tried setting mothershipProviderID in the config to some other value?

**Comment by Rory0merchury** [comment]
i will try....

**Comment by Rory0merchury** [comment]
awright turns out i had to change the MothershipproviderID

**Comment by katzenpapst** [comment]
Could you give me a list of your mods? I still have no idea why exactly this happens. 
I added a check, though, which should tell you to change the provider ID if that happens again. I'm not entirely sure how accurate this check is, though.

**Comment by Rory0merchury** [comment]
here ive made the modlist before For Augitesoul
Heres the past bin
http://pastebin.com/8uen9yw8

**Comment by katzenpapst** [comment]
Well, I'll just close this for now.
