### ISSUE TITLE
Crash with Machine as FallingSand

### ISSUE THREAD

**Issue by RandomIntel** [katzenpapst/amunra#24]
(I originally discovered this by breaking a spinning ReactorCraft Hysteresis Magnet near a Mothership Navigation Console, but I have since isolated the cause.)

It appears to happen when a FallingSand entity representing an Amun-Ra machine tries to land.

Crash Reeport: [crash-2017-02-22_13.10.34-server.txt](https://github.com/katzenpapst/amunra/files/794738/crash-2017-02-22_13.10.34-server.txt)

* Steps to reproduce:

  * The Setup:
![2017-02-22_13 05 53](https://cloud.githubusercontent.com/assets/22619104/23230551/b267d960-f901-11e6-8b77-388fc6e06caf.png)

  * (410/2) is the ID of the Mothership Navigation Console:
![2017-02-22_13 10 02](https://cloud.githubusercontent.com/assets/22619104/23230562/bce5a44e-f901-11e6-8702-90a52ba36239.png)

  * This screenshot is from right after I activated the command block, and right before the FallingSand lands. The FallingSand landing causes the crash:
![2017-02-22_13 10 34](https://cloud.githubusercontent.com/assets/22619104/23230986/375eb2a0-f903-11e6-9a3e-b0509a573427.png)

**Comment by katzenpapst** [comment]
What the... why would ReactorCraft make falling sand entities out of random blocks?

Anyway, thanks for the detailed bug report. I made a fix which *MIGHT* work, if the actual ReactorCraft code also adds the actual meta value to the fallingblock. If it doesn't, well, I'd say that's a bug on RC's side. (Otherwise the console will turn into a radioisotope generator)

**Comment by RandomIntel** [comment]
On the topic of ReactorCraft: Making falling blocks is just RC's way of making its own Event, for Rapid Unscheduled Disassembly of its MultiBlocks. Also, Reika is far to good to allow a bug like that to *not* get fixed.

Also, I just tried changing the command to "summon FallingSand ~ ~1.5 ~2 {TileID:410,**Data:14**}"

14 is the meta for that direction of MSNC, so we know it's not that.

**Comment by katzenpapst** [comment]
Oh, that's how you do it. I googled about spawning sand with meta, but didn't find anything.

**Comment by katzenpapst** [comment]
Hm, this should be fixed in 0.4+
