### ISSUE TITLE
Make mothership commands at op level 1

### ISSUE THREAD

**Issue by AugiteSoul** [katzenpapst/amunra#29]
If executed by a non-player op, it should return the dimension where command is executed, then it should follow 2 conditions:
1: Is dimension a MS? if true then check cond. 2 else return error
2: Is MS in transit? if true stop transit else return error

Because I want to make some sort of warping system, who warps instantly a ship on a body.

**Comment by katzenpapst** [comment]
Okay, after some googling I decided to set the op level to 2. If that's what /give uses, I think it should be the same here. I successfully was able to use /mothership_move in a command block with it. 

I also added an optional parameter to /mothership_move, to set the travel time. By default, it will still use 100 ticks (This command can't do any actual travel time calculation anyway)
