### ISSUE TITLE
Server incompatability.

### ISSUE THREAD

**Issue by KingOfMiners** [katzenpapst/amunra#5]
The latest version of AmunRa does not work on servers because servers don't have LWJGL but the add-on requires it. Crash report: http://pastebin.com/5UFtTp2P

**Comment by katzenpapst** [comment]
Removed it from everything non-client, should be fixed in next build

**Comment by KingOfMiners** [comment]
Doesn't the AmunRa class reference Vector3f when registering planets?

**Comment by katzenpapst** [comment]
It did, which was a mistake. I changed it to the Vector3 class from micdoodle
