### ISSUE TITLE
A question about the mod.

### ISSUE THREAD

**Issue by thiago1255** [katzenpapst/amunra#55]
Hello ! I would like to ask you something, will the mod update to 1.12.2? And could I try to update it?

I really liked the mod, but I wanted to play in version 1.12.2 :(

(I'm using google translator)

**Comment by boot2big** [comment]
Quote from dev: "I am sorry, but I don't think I will return to the development of this addon anytime soon.

You are free to fork this project and to continue development, if you can do any java..."

**Comment by thiago1255** [comment]
> Quote from dev: "I am sorry, but I don't think I will return to the development of this addon anytime soon.
> 
> You are free to fork this project and to continue development, if you can do any java..."

Thanks !

 Could I change the name of the mod and add more things to the mod? (of course I keep credits to the creator of the mod)

**Comment by boot2big** [comment]
Probably? I'm not the dev.

**Comment by praecipitator** [comment]
Yes, do it.

**Comment by thiago1255** [comment]
> Yes, do it.

Ok, thanks! I'll see if I can update the mod.

**Comment by thiago1255** [comment]
Just one more question, has anyone started to update or will I be the first person to try this?

**Comment by praecipitator** [comment]
Not that I'm aware of. I think you are the first one, yes.
