### ISSUE TITLE
Motherships won't work on servers.

### ISSUE THREAD

**Issue by KingOfMiners** [katzenpapst/amunra#7]
When ever you use the shuttle rocket it works fine but when you try to create a mothership the server kicks everyone with the message: "A fatal error has occured."

**Comment by katzenpapst** [comment]
Do you have a crash report as well?

**Comment by KingOfMiners** [comment]
It doesn't crash, It just kicks. The only time it crashes is when you go to a singleplayer world after your kicked. http://pastebin.com/Xi7aN9Ga

**Comment by katzenpapst** [comment]
Eh, being able to use another world after you left one is a whole different story altogether... But anyway, I fixed the main issue now, I think

**Comment by KingOfMiners** [comment]
You can create a mothership and go onto it but if you leave and rejoin it kicks you.

**Comment by katzenpapst** [comment]
Please give a more detailed description. You mean, you have a server/client setup, you join the game, then go to a mothership, leave the game there, then rejoin the server, and it instantly kicks you out?
BTW, you should have a "logs" directory on your client as well, there should be files like "latest.log" and "fml-client-latest.log". There might be a crash report there.

**Comment by KingOfMiners** [comment]
http://pastebin.com/ZFKCEakY
